
before_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"

stages:
    - build
    - test
    - deploy

build:
  stage: build
  only:
    - dummy
  script:
    - cd ..\Arch(.NetCore)
    - dotnet restore Bhbk.WebApi.Aurora.sln --no-cache --verbosity minimal
    - dotnet build Bhbk.WebApi.Aurora.sln --configuration Release --verbosity minimal /p:platform=x64

test:
  stage: test
  only:
    - dummy
  script:
    - cd ..\Arch(.NetCore)
    - dotnet restore Bhbk.WebApi.Aurora.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.WebApi.Aurora.sln --configuration Release --verbosity quiet /p:platform=x64
    - dotnet test Bhbk.Daemon.Aurora.Tests\Bhbk.Daemon.Aurora.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Aurora.Tests\Bhbk.WebApi.Aurora.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\

deploy:
  stage: deploy
  only:
    - dummy
  script:
    - set VERSION=2020.04.06.2030
    - cd ..\Arch(.NetCore)
    - dotnet restore Bhbk.WebApi.Aurora.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.WebApi.Aurora.sln --configuration Release --verbosity quiet /p:platform=x64
    - dotnet pack Bhbk.Lib.Aurora\Bhbk.Lib.Aurora.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - dotnet publish Bhbk.Cli.Aurora\Bhbk.Cli.Aurora.csproj --output Bhbk.Cli.Aurora\bin\Release\netcoreapp3.1\publish --configuration Release /p:platform=x64
    - dotnet publish Bhbk.Daemon.Aurora\Bhbk.Daemon.Aurora.csproj --output Bhbk.Daemon.Aurora\bin\Release\netcoreapp3.1\publish --configuration Release /p:platform=x64
    - dotnet publish Bhbk.WebApi.Aurora\Bhbk.WebApi.Aurora.csproj --output Bhbk.WebApi.Aurora\bin\Release\netcoreapp3.1\publish --configuration Release /p:platform=x64
    - dotnet octo pack --id=Bhbk.Cli.Aurora --version=%VERSION% --basePath=Bhbk.Cli.Aurora\bin\Release\netcoreapp3.1\publish --outFolder=.
    - dotnet octo pack --id=Bhbk.Daemon.Aurora --version=%VERSION% --basePath=Bhbk.Daemon.Aurora\bin\Release\netcoreapp3.1\publish --outFolder=.
    - dotnet octo pack --id=Bhbk.WebApi.Aurora --version=%VERSION% --basePath=Bhbk.WebApi.Aurora\bin\Release\netcoreapp3.1\publish --outFolder=.
    - cd ..
    - dotnet nuget push Arch(.NetCore)\*.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
    - set VERSION=
