
before_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"

stages:
    - build
    - test
    - deploy

build:
  stage: build
  only:
    - dummy
  script:
    - pushd Arch(.NetCore)
    - nuget restore Bhbk.Lib.Aurora.Data.EF6\Bhbk.Lib.Aurora.Data.EF6.csproj -SolutionDirectory . -Verbosity quiet
    - dotnet restore Bhbk.Aurora.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Aurora.sln --configuration Release --verbosity quiet
    - popd

test:
  stage: test
  only:
    - dummy
  script:
    - pushd Arch(.NetCore)
    - nuget restore Bhbk.Lib.Aurora.Data.EF6\Bhbk.Lib.Aurora.Data.EF6.csproj -SolutionDirectory . -Verbosity quiet
    - dotnet restore Bhbk.Aurora.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Aurora.sln --configuration Release --verbosity quiet
    - dotnet test Bhbk.Lib.Aurora.Data.Tests\Bhbk.Lib.Aurora.Data.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.Lib.Aurora.Data_EF6.Tests\Bhbk.Lib.Aurora.Data_EF6.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.Daemon.Aurora.FTP.Tests\Bhbk.Daemon.Aurora.FTP.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.Daemon.Aurora.SSH.Tests\Bhbk.Daemon.Aurora.SSH.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Aurora.Tests\Bhbk.WebApi.Aurora.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - popd

deploy:
  stage: deploy
  only:
    - dummy
  script:
    - set AURORAVERSION=2020.11.27.2100
    - pushd Arch(.NetCore)
    - nuget restore Bhbk.Lib.Aurora.Data.EF6\Bhbk.Lib.Aurora.Data.EF6.csproj -SolutionDirectory . -Verbosity quiet
    - dotnet restore Bhbk.Aurora.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Aurora.sln --configuration Release --verbosity quiet
    - dotnet pack Bhbk.Lib.Aurora\Bhbk.Lib.Aurora.csproj -p:PackageVersion=%AURORAVERSION% --output . --configuration Release
    - dotnet publish Bhbk.Daemon.Aurora.FTP\Bhbk.Daemon.Aurora.FTP.csproj --output Bhbk.Daemon.Aurora.FTP\bin\Release\net5.0\publish\ --configuration Release
    - dotnet publish Bhbk.Daemon.Aurora.SSH\Bhbk.Daemon.Aurora.SSH.csproj --output Bhbk.Daemon.Aurora.SSH\bin\Release\net5.0\publish\ --configuration Release
    - dotnet publish Bhbk.WebApi.Aurora\Bhbk.WebApi.Aurora.csproj --output Bhbk.WebApi.Aurora\bin\Release\net5.0\publish\ --configuration Release
    - dotnet octo pack --id=Bhbk.Cli.Aurora --version=%AURORAVERSION% --basePath=Bhbk.Cli.Aurora\bin\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.Daemon.Aurora.FTP --version=%AURORAVERSION% --basePath=Bhbk.Daemon.Aurora.FTP\bin\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.Daemon.Aurora.SSH --version=%AURORAVERSION% --basePath=Bhbk.Daemon.Aurora.SSH\bin\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.WebApi.Aurora --version=%AURORAVERSION% --basePath=Bhbk.WebApi.Aurora\bin\Release\net5.0\publish\ --outFolder=. --overwrite
    - popd
    - pushd Arch(.NetCore)
    - dotnet nuget push *.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
    - popd
    - set AURORAVERSION=
