
before_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"

stages:
    - build
    - test
    - deploy

build:
  stage: build
  only:
    - dummy
  script:
    - cd ..\Arch(.NetCore)
    - nuget restore Bhbk.Lib.Aurora.Data.EF6\Bhbk.Lib.Aurora.Data.EF6.csproj -SolutionDirectory . -Verbosity quiet
    - dotnet restore Bhbk.Aurora.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Aurora.sln --configuration Release --verbosity quiet /p:platform=x64

test:
  stage: test
  only:
    - dummy
  script:
    - cd ..\Arch(.NetCore)
    - nuget restore Bhbk.Lib.Aurora.Data.EF6\Bhbk.Lib.Aurora.Data.EF6.csproj -SolutionDirectory . -Verbosity quiet
    - dotnet restore Bhbk.Aurora.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Aurora.sln --configuration Release --verbosity quiet /p:platform=x64
    - dotnet test Bhbk.Daemon.Aurora.FTP.Tests\Bhbk.Daemon.Aurora.FTP.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.Daemon.Aurora.SSH.Tests\Bhbk.Daemon.Aurora.SSH.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\
    - dotnet test Bhbk.WebApi.Aurora.Tests\Bhbk.WebApi.Aurora.Tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=bin\Release\

deploy:
  stage: deploy
  only:
    - dummy
  script:
    - set VERSION=2020.11.21.2300
    - cd ..\Arch(.NetCore)
    - nuget restore Bhbk.Lib.Aurora.Data.EF6\Bhbk.Lib.Aurora.Data.EF6.csproj -SolutionDirectory . -Verbosity quiet
    - dotnet restore Bhbk.Aurora.sln --no-cache --verbosity quiet
    - dotnet build Bhbk.Aurora.sln --configuration Release --verbosity quiet /p:platform=x64
    - dotnet pack Bhbk.Lib.Aurora\Bhbk.Lib.Aurora.csproj -p:PackageVersion=%VERSION% --output . --configuration Release /p:platform=x64
    - dotnet publish Bhbk.Daemon.Aurora.FTP\Bhbk.Daemon.Aurora.FTP.csproj --output Bhbk.Daemon.Aurora.FTP\bin\x64\Release\net5.0\publish\ --configuration Release /p:platform=x64
    - dotnet publish Bhbk.Daemon.Aurora.SSH\Bhbk.Daemon.Aurora.SSH.csproj --output Bhbk.Daemon.Aurora.SSH\bin\x64\Release\net5.0\publish\ --configuration Release /p:platform=x64
    - dotnet publish Bhbk.WebApi.Aurora\Bhbk.WebApi.Aurora.csproj --output Bhbk.WebApi.Aurora\bin\x64\Release\net5.0\publish\ --configuration Release /p:platform=x64
    - dotnet octo pack --id=Bhbk.Cli.Aurora --version=%VERSION% --basePath=Bhbk.Cli.Aurora\bin\x64\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.Daemon.Aurora.FTP --version=%VERSION% --basePath=Bhbk.Daemon.Aurora.FTP\bin\x64\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.Daemon.Aurora.SSH --version=%VERSION% --basePath=Bhbk.Daemon.Aurora.SSH\bin\x64\Release\net5.0\publish\ --outFolder=. --overwrite
    - dotnet octo pack --id=Bhbk.WebApi.Aurora --version=%VERSION% --basePath=Bhbk.WebApi.Aurora\bin\x64\Release\net5.0\publish\ --outFolder=. --overwrite
    - cd ..
    - dotnet nuget push Arch(.NetCore)\*.nupkg --api-key %NUGET_FEED_KEY% --source %NUGET_FEED_URL%
    - set VERSION=
