//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhbk.Lib.Aurora.Data_EF6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivateKey_EF
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public System.Guid PublicKeyId { get; set; }
        public string KeyValue { get; set; }
        public int KeyAlgorithmId { get; set; }
        public int KeyFormatId { get; set; }
        public string EncryptedPass { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeletable { get; set; }
        public System.DateTimeOffset CreatedUtc { get; set; }
    
        public virtual PrivateKeyFormatType_EF KeyFormatType { get; set; }
        public virtual KeyAlgorithmType_EF KeyAlgorithmType { get; set; }
        public virtual Login_EF Login { get; set; }
    }
}
